site_name: "Sean Hu"
site_description: "Projects + notes across ML systems, biomaterials, and computational + synthetic biology."
site_url: "https://seanhu0401.github.io"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
